
-- 6.) Join the necessary tables to find the total quantity of each pizza category ordered.

	SELECT 
		PIZZA_TYPES.CATEGORY ,
		SUM(ORDER_DETAILS.QUANTITY) AS QUANTITY 
        
	FROM PIZZAS JOIN ORDER_DETAILS
	ON PIZZAS.PIZZA_ID = ORDER_DETAILS.PIZZA_ID

	JOIN PIZZA_TYPES           -- 3 rd table joined. 
	ON PIZZA_TYPES.PIZZA_TYPE_ID = PIZZAS.PIZZA_TYPE_ID

	GROUP BY PIZZA_TYPES.CATEGORY
	ORDER BY QUANTITY DESC ;
    
    
-- 7.) Determine the distribution of orders by hour of the day.

	SELECT 
		HOUR(TIME) AS HOURS , 
        COUNT(ORDER_ID) AS ORDER_COUNT
	FROM ORDERS
	GROUP BY HOUR(TIME);  


-- 8.) Join relevant tables to find the category-wise distribution of pizzas.


	SELECT CATEGORY , COUNT(NAME) FROM PIZZA_TYPES
    GROUP BY CATEGORY ;
    
    
    
-- 9.) How many orders does each pizza category receive during different time slots (Morning, Afternoon, Evening, Night) in a day?
   
   
   SELECT 
		PIZZA_TYPES.CATEGORY,
		CASE 
			WHEN HOUR(ORDERS.TIME) BETWEEN 6 AND 11 THEN 'Morning'
			WHEN HOUR(ORDERS.TIME) BETWEEN 12 AND 16 THEN 'Afternoon'
			WHEN HOUR(ORDERS.TIME) BETWEEN 17 AND 21 THEN 'Evening'
			ELSE 'Night'
		END AS TIME_SLOT,
    COUNT(ORDER_DETAILS.ORDER_ID) AS TOTAL_ORDERS

	FROM PIZZA_TYPES  JOIN PIZZAS 
    ON PIZZAS.PIZZA_TYPE_ID = PIZZA_TYPES.PIZZA_TYPE_ID

	JOIN ORDER_DETAILS
    ON ORDER_DETAILS.PIZZA_ID = PIZZAS.PIZZA_ID

	JOIN ORDERS
    ON ORDERS.ORDER_ID = ORDER_DETAILS.ORDER_ID

	GROUP BY PIZZA_TYPES.CATEGORY , TIME_SLOT
	ORDER BY PIZZA_TYPES.CATEGORY , TOTAL_ORDERS DESC;


-- 10.) Group the orders by date and calculate the average number of pizzas ordered per day.

	SELECT ROUND(AVG(QUANTITY),0) AS AVG_PIZZAS_ORDERD_PER_DAY
    FROM
    
    (SELECT ORDERS.DATE  ,  SUM(ORDER_DETAILS.QUANTITY) AS QUANTITY
	FROM ORDERS JOIN ORDER_DETAILS
    ON ORDERS.ORDER_ID = ORDER_DETAILS.ORDER_ID
	GROUP BY ORDERS.DATE) AS ORDER_QUANTITY ;


-- 11.) Determine the top 3 most ordered pizza types based on revenue.

SELECT PIZZA_TYPES.NAME , 
SUM(ORDER_DETAILS.QUANTITY * PIZZAS.PRICE) AS REVENUE
FROM PIZZAS JOIN PIZZA_TYPES
ON PIZZAS.PIZZA_TYPE_ID = PIZZA_TYPES.PIZZA_TYPE_ID

JOIN ORDER_DETAILS
ON ORDER_DETAILS.PIZZA_ID = PIZZAS.PIZZA_ID

GROUP BY PIZZA_TYPES.NAME
ORDER BY REVENUE DESC LIMIT 3 ;



