
-- 12.) Calculate the percentage contribution of each pizza type to total revenue.


	SELECT PIZZA_TYPES.CATEGORY , 
	ROUND(SUM(ORDER_DETAILS.QUANTITY * PIZZAS.PRICE) / (SELECT 
			ROUND(SUM(ORDER_DETAILS.QUANTITY * PIZZAS.PRICE),2) AS TOTAL_REVENUE
		FROM ORDER_DETAILS JOIN PIZZAS
		ON PIZZAS.PIZZA_ID = ORDER_DETAILS.PIZZA_ID ) * 100,2) AS REVENUE
    
	FROM PIZZAS JOIN PIZZA_TYPES
	ON PIZZAS.PIZZA_TYPE_ID = PIZZA_TYPES.PIZZA_TYPE_ID

	JOIN ORDER_DETAILS
	ON ORDER_DETAILS.PIZZA_ID = PIZZAS.PIZZA_ID

	GROUP BY PIZZA_TYPES.CATEGORY
	ORDER BY REVENUE DESC ;



 -- 13.) Analyze the cumulative revenue generated over time.
 
	SELECT DATE ,
	SUM(REVENUE) OVER (ORDER BY DATE ) AS 'cumulative revenue'
	 FROM
        (SELECT ORDERS.DATE,
		SUM(ORDER_DETAILS.QUANTITY * PIZZAS.PRICE) AS REVENUE
    
		FROM ORDER_DETAILS JOIN PIZZAS
		ON ORDER_DETAILS.PIZZA_ID = PIZZAS.PIZZA_ID
        
        JOIN ORDERS
        ON ORDERS.ORDER_ID = ORDER_DETAILS.ORDER_ID
        
        GROUP BY  ORDERS.DATE ) AS SALES;
        
        
        
        
-- 14.) Determine the top 3 most ordered pizza types based on revenue for each pizza category.

SELECT NAME,REVENUE
FROM
(WITH MY_CTE AS (SELECT PIZZA_TYPES.CATEGORY,
PIZZA_TYPES.NAME,
SUM(ORDER_DETAILS.QUANTITY * PIZZAS.PRICE) AS REVENUE

FROM PIZZA_TYPES JOIN PIZZAS
ON PIZZA_TYPES.PIZZA_TYPE_ID = PIZZAS.PIZZA_TYPE_ID

JOIN ORDER_DETAILS
ON ORDER_DETAILS.PIZZA_ID = PIZZAS.PIZZA_ID

GROUP BY PIZZA_TYPES.CATEGORY, PIZZA_TYPES.NAME)

SELECT CATEGORY , NAME, REVENUE,
RANK() OVER(PARTITION BY CATEGORY
			ORDER BY REVENUE DESC) AS RANKS
            FROM MY_CTE) AS SUB_Q
WHERE RANKS<= 3; 
