CREATE DATABASE PIZZA_SALES;
USE PIZZA_SALES;


--  1.) total number of orders placed.

	SELECT COUNT(ORDER_ID) 	AS TOTAL_ORDERS FROM ORDER_DETAILS;


-- 2.) total revenue generated from pizza sales.

	SELECT 
		ROUND(SUM(ORDER_DETAILS.QUANTITY * PIZZAS.PRICE),2) AS TOTAL_REVENUE
	FROM ORDER_DETAILS JOIN PIZZAS
	ON PIZZAS.PIZZA_ID = ORDER_DETAILS.PIZZA_ID ;


-- 3.) Identify the highest-priced pizza.

	SELECT PIZZA_TYPES.NAME , PIZZAS.PRICE
	FROM  PIZZA_TYPES JOIN PIZZAS
	ON PIZZA_TYPES.PIZZA_TYPE_ID = PIZZAS.PIZZA_TYPE_ID
    ORDER BY  PIZZAS.PRICE DESC  LIMIT 1 ;
    
    
-- Q.) Highest-priced pizza per category 

	SELECT 
		MAX(PIZZAS.PRICE) AS MAX_PRICE ,
		PIZZA_TYPES.CATEGORY
	FROM PIZZAS JOIN PIZZA_TYPES
	ON PIZZAS.PIZZA_TYPE_ID = PIZZA_TYPES.PIZZA_TYPE_ID
	GROUP BY PIZZA_TYPES.CATEGORY 
	ORDER BY MAX_PRICE DESC ;
    
    
--  4.) Identify the most common pizza size ordered.

	SELECT 
	PIZZAS.SIZE, COUNT(ORDER_DETAILS.ORDER_DETAILS_ID) AS ORDER_COUNT
	FROM PIZZAS JOIN ORDER_DETAILS
	ON PIZZAS.PIZZA_ID = ORDER_DETAILS.PIZZA_ID
	GROUP BY PIZZAS.SIZE 
    ORDER BY ORDER_COUNT DESC;


SELECT QUANTITY, COUNT(ORDER_DETAILS_ID)  -- Q.)most common pizza QUANTITYS ordered.
FROM ORDER_DETAILS GROUP BY QUANTITY;



-- 5.) List the top 5 most ordered pizza types along with their quantities.

	SELECT 
		PIZZA_TYPES.NAME ,
        PIZZAS.PIZZA_TYPE_ID  , 
		SUM(ORDER_DETAILS.QUANTITY) AS QUANTITY 
        
	FROM PIZZAS JOIN ORDER_DETAILS
	ON PIZZAS.PIZZA_ID = ORDER_DETAILS.PIZZA_ID

	JOIN PIZZA_TYPES           -- 3 rd table joined. 
	ON PIZZA_TYPES.PIZZA_TYPE_ID = PIZZAS.PIZZA_TYPE_ID

	GROUP BY PIZZAS.PIZZA_TYPE_ID, PIZZA_TYPES.NAME
	ORDER BY QUANTITY DESC LIMIT 5;



